# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LiuQingshuo\memorizeWords\UI\CETest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 200)
        Form.setWindowTitle("")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(53, 120, 190, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.backbutton = QtWidgets.QPushButton(Form)
        self.backbutton.setGeometry(QtCore.QRect(0, 0, 30, 30))
        self.backbutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backbutton.setIcon(icon)
        self.backbutton.setFlat(True)
        self.backbutton.setObjectName("backbutton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(59, 40, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 160, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setText(_translate("Form", "下一个"))
import resource_rc
